# Generated by Django 4.1.7 on 2023-04-27 21:08

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('time_reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttime',
            name='hours',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='projecttime',
            name='rate',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='PLN', max_digits=6),
        ),
    ]
