# Generated by Django 4.1.3 on 2023-01-12 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_rename_contract_name_contract_name_and_more'),
        ('projects', '0004_project_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='members', to='employees.employee'),
        ),
    ]
