# Generated by Django 4.1.3 on 2022-12-08 09:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('nip', models.CharField(blank=True, max_length=20, null=True)),
                ('avatar', models.ImageField(blank=True, upload_to='EmployeeAvatar/')),
                ('avatar_checksum', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
