# Generated by Django 4.1.3 on 2022-12-15 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_contract'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract',
            old_name='name',
            new_name='contract_name',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='file',
        ),
        migrations.AddField(
            model_name='contract',
            name='contract_scan',
            field=models.FileField(blank=True, upload_to='EmployeeContract/'),
        ),
    ]
