# Generated by Django 4.1.3 on 2023-01-05 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_rate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rate',
            old_name='chargable_rate',
            new_name='chargable',
        ),
        migrations.RenameField(
            model_name='rate',
            old_name='chargable_rate_currency',
            new_name='chargable_currency',
        ),
        migrations.RenameField(
            model_name='rate',
            old_name='internal_rate',
            new_name='internal',
        ),
        migrations.RenameField(
            model_name='rate',
            old_name='internal_rate_currency',
            new_name='internal_currency',
        ),
    ]
