# Generated by Django 4.1.3 on 2023-01-06 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_rename_chargable_rate_rate_chargable_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract',
            old_name='contract_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='contract',
            old_name='contract_scan',
            new_name='scan',
        ),
        migrations.RenameField(
            model_name='contract',
            old_name='contract_type',
            new_name='type',
        ),
    ]
